import mongoose from "mongoose";
import dotenv from "dotenv";
import Customer from "../models/Customer.js";

dotenv.config();

const data = [
  {
    customerId: 1,
    customerName: "John Doe",
    phoneNumber: "1234567890",
    gender: "Male",
    customerRegion: "North",
    productCategory: "Electronics",
    tags: ["New"],
    paymentMethod: "Cash",
    quantity: 5,
    date: new Date("2025-12-01T10:00:00Z"),
  },
  {
    customerId: 2,
    customerName: "Jane Smith",
    phoneNumber: "9876543210",
    gender: "Female",
    customerRegion: "South",
    productCategory: "Furniture",
    tags: ["Sale"],
    paymentMethod: "Card",
    quantity: 2,
    date: new Date("2025-12-02T11:30:00Z"),
  },
  {
    customerId: 3,
    customerName: "Alice Johnson",
    phoneNumber: "5555555555",
    gender: "Female",
    customerRegion: "North",
    productCategory: "Electronics",
    tags: ["New", "Sale"],
    paymentMethod: "Cash",
    quantity: 3,
    date: new Date("2025-12-03T09:20:00Z"),
  },
  {
    customerId: 4,
    customerName: "Bob Williams",
    phoneNumber: "4444444444",
    gender: "Male",
    customerRegion: "South",
    productCategory: "Furniture",
    tags: ["New"],
    paymentMethod: "Card",
    quantity: 4,
    date: new Date("2025-12-04T14:45:00Z"),
  },
  {
    customerId: 5,
    customerName: "Charlie Brown",
    phoneNumber: "1111111111",
    gender: "Male",
    customerRegion: "North",
    productCategory: "Grocery",
    tags: ["Bulk"],
    paymentMethod: "UPI",
    quantity: 12,
    date: new Date("2025-12-05T08:10:00Z"),
  },
  {
    customerId: 6,
    customerName: "Diana Prince",
    phoneNumber: "2222222222",
    gender: "Female",
    customerRegion: "South",
    productCategory: "Clothing",
    tags: ["New"],
    paymentMethod: "Card",
    quantity: 6,
    date: new Date("2025-12-06T16:00:00Z"),
  },
  {
    customerId: 7,
    customerName: "Eve Summers",
    phoneNumber: "3333333333",
    gender: "Female",
    customerRegion: "North",
    productCategory: "Beauty",
    tags: ["Sale"],
    paymentMethod: "Cash",
    quantity: 1,
    date: new Date("2025-12-07T12:05:00Z"),
  },
  {
    customerId: 8,
    customerName: "Frank Miller",
    phoneNumber: "4444440000",
    gender: "Male",
    customerRegion: "South",
    productCategory: "Electronics",
    tags: ["Refurbished"],
    paymentMethod: "Card",
    quantity: 2,
    date: new Date("2025-12-08T13:30:00Z"),
  },
  {
    customerId: 9,
    customerName: "Grace Lee",
    phoneNumber: "5555551212",
    gender: "Female",
    customerRegion: "North",
    productCategory: "Home Decor",
    tags: ["New"],
    paymentMethod: "UPI",
    quantity: 7,
    date: new Date("2025-12-09T09:50:00Z"),
  },
  {
    customerId: 10,
    customerName: "Henry Ford",
    phoneNumber: "6666666666",
    gender: "Male",
    customerRegion: "South",
    productCategory: "Automotive",
    tags: ["Spare"],
    paymentMethod: "Cash",
    quantity: 1,
    date: new Date("2025-12-10T17:20:00Z"),
  },
  {
    customerId: 11,
    customerName: "Ivy Green",
    phoneNumber: "7777777777",
    gender: "Female",
    customerRegion: "North",
    productCategory: "Books",
    tags: ["New"],
    paymentMethod: "Card",
    quantity: 9,
    date: new Date("2025-12-11T10:15:00Z"),
  },
  {
    customerId: 12,
    customerName: "Jack Black",
    phoneNumber: "8888888888",
    gender: "Male",
    customerRegion: "East",
    productCategory: "Electronics",
    tags: ["Sale"],
    paymentMethod: "UPI",
    quantity: 3,
    date: new Date("2025-12-12T11:11:00Z"),
  },
  {
    customerId: 13,
    customerName: "Kiran Patel",
    phoneNumber: "9999990000",
    gender: "Male",
    customerRegion: "West",
    productCategory: "Clothing",
    tags: ["New"],
    paymentMethod: "Card",
    quantity: 4,
    date: new Date("2025-12-13T15:40:00Z"),
  },
  {
    customerId: 14,
    customerName: "Lina Gomez",
    phoneNumber: "1010101010",
    gender: "Female",
    customerRegion: "East",
    productCategory: "Grocery",
    tags: ["Organic"],
    paymentMethod: "Cash",
    quantity: 20,
    date: new Date("2025-12-14T07:30:00Z"),
  },
  {
    customerId: 15,
    customerName: "Mohan Singh",
    phoneNumber: "1212121212",
    gender: "Male",
    customerRegion: "West",
    productCategory: "Electronics",
    tags: ["New"],
    paymentMethod: "Card",
    quantity: 2,
    date: new Date("2025-12-15T18:05:00Z"),
  },
  {
    customerId: 16,
    customerName: "Nisha Rao",
    phoneNumber: "1313131313",
    gender: "Female",
    customerRegion: "East",
    productCategory: "Beauty",
    tags: ["Sale"],
    paymentMethod: "UPI",
    quantity: 5,
    date: new Date("2025-12-16T14:00:00Z"),
  },
  {
    customerId: 17,
    customerName: "Omar Ali",
    phoneNumber: "1414141414",
    gender: "Male",
    customerRegion: "West",
    productCategory: "Home Decor",
    tags: ["Limited"],
    paymentMethod: "Cash",
    quantity: 2,
    date: new Date("2025-12-17T09:45:00Z"),
  },
  {
    customerId: 18,
    customerName: "Priya Sharma",
    phoneNumber: "1515151515",
    gender: "Female",
    customerRegion: "East",
    productCategory: "Books",
    tags: ["New"],
    paymentMethod: "Card",
    quantity: 6,
    date: new Date("2025-12-18T12:25:00Z"),
  },
  {
    customerId: 19,
    customerName: "Quentin Tarun",
    phoneNumber: "1616161616",
    gender: "Male",
    customerRegion: "West",
    productCategory: "Furniture",
    tags: ["Sale"],
    paymentMethod: "UPI",
    quantity: 3,
    date: new Date("2025-12-19T16:10:00Z"),
  },
  {
    customerId: 20,
    customerName: "Riya Verma",
    phoneNumber: "1717171717",
    gender: "Female",
    customerRegion: "North",
    productCategory: "Clothing",
    tags: ["New", "Limited"],
    paymentMethod: "Card",
    quantity: 8,
    date: new Date("2025-12-20T13:00:00Z"),
  },
];

const run = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Customer.deleteMany({});
    await Customer.insertMany(data);
    console.log("Seed data inserted successfully!");
  } catch (err) {
    console.error("Error seeding data:", err);
  } finally {
    process.exit();
  }
};

run();
